- title: Jekyll Theme
  path: assets/img/ui.svg
  details: There are many areas of design. UI, UX, product designers, graphic designers, interaction designers, information architec. 

- title: Jekyll Design
  path: assets/img/web-design.svg
  details: There are many areas of design. UI, UX, product designers, graphic designers, interaction designers, information architec.

- title: Tami Ubaidah
  path: assets/img/programming.svg
  details: There are many areas of design. UI, UX, product designers,  graphic designers, interaction designers, information architec.

- title: Graphic dedign
  path: assets/img/coding.svg
  details: There are many areas of design. UI, UX, product designers,  graphic designers, interaction designers, information architec.

- title: Graphic dedign
  path: assets/img/graphic-design.svg
  details: There are many areas of design. UI, UX, product designers,  graphic designers, interaction designers, information architec.

- title: Graphic dedign
  path: assets/img/seo.svg
  details: There are many areas of design. UI, UX, product designers,  graphic designers, interaction designers, information architec.

- title: Graphic dedign
  path: assets/img/ui.svg
  details: There are many areas of design. UI, UX, product designers,  graphic designers, interaction designers, information architec.